{% set name = "zenith" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bvaisvil/zenith/archive/{{ version }}.tar.gz
  sha256: 73d704b3cbf93506c22f3a7d98ae1a75011434a27a978dd0a7b6b30c7794423b

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - libclang

test:
  commands:
    - zenith --help

about:
  home: https://github.com/bvaisvil/zenith
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: In terminal graphical metrics for your *nix system
  dev_url: https://github.com/bvaisvil/zenith

extra:
  recipe-maintainers:
    - danielnachun
