context:
  version: "0.14.2"

package:
  name: zenith
  version: ${{ version }}

source:
  url: https://github.com/bvaisvil/zenith/archive/${{ version }}.tar.gz
  sha256: 5fa6873a5a1182067ed7f0355521bdb35498980b5b751f26e2e6fed93474dcf9

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - libclang

tests:
  - script:
      - zenith --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: In terminal graphical metrics for your *nix system
  homepage: https://github.com/bvaisvil/zenith
  repository: https://github.com/bvaisvil/zenith

extra:
  recipe-maintainers:
    - danielnachun
