context:
  version: 0.14.1

package:
  name: zenith
  version: ${{ version }}

source:
  url: https://github.com/bvaisvil/zenith/archive/${{ version }}.tar.gz
  sha256: 73d704b3cbf93506c22f3a7d98ae1a75011434a27a978dd0a7b6b30c7794423b

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - libclang

tests:
  - script:
      - zenith --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: In terminal graphical metrics for your *nix system
  homepage: https://github.com/bvaisvil/zenith
  repository: https://github.com/bvaisvil/zenith

extra:
  recipe-maintainers:
    - danielnachun
